version: '3.9'

services:
  app:
    build: .
    container_name: tech-challenge-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: challengedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
